export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIELIST = "FETCH_MOVIELIST";
export const CATEGORY_SELECT = "CATEGORY_SELECT";
export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const PAGE_NEXT = "PAGE_NEXT";
export const MOVIE_SELECTED = "MOVIE_SELECTED";
